import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { 
  Building2, 
  Shield, 
  Download, 
  Crown, 
  CheckCircle, 
  AlertTriangle,
  FileText,
  Globe,
  Mail,
  Phone,
  MapPin
} from "lucide-react";
import { PremiumUpgradeModal } from "@/components/PremiumUpgradeModal";
import { useNavigate } from "react-router-dom";

const VendorDashboard = () => {
  const [showPremiumModal, setShowPremiumModal] = useState(false);
  const navigate = useNavigate();

  // Mock vendor data - in real app, this would come from your backend
  const vendorData = {
    name: "TechCorp Solutions Pvt Ltd",
    gstin: "29ABCDE1234F1Z5",
    pan: "ABCDE1234F",
    address: "123 Tech Park, Bangalore, Karnataka 560001",
    email: "contact@techcorp.com",
    phone: "+91 9876543210",
    website: "https://techcorp.com",
    isVerified: true,
    isPremium: false,
    verificationStatus: {
      gstin: "verified",
      pan: "verified",
      documents: "pending",
      reputation: "verified"
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "verified":
        return <CheckCircle className="h-4 w-4 text-green-600" />;
      case "pending":
        return <AlertTriangle className="h-4 w-4 text-yellow-600" />;
      default:
        return <AlertTriangle className="h-4 w-4 text-red-600" />;
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "verified":
        return "bg-green-100 text-green-800";
      case "pending":
        return "bg-yellow-100 text-yellow-800";
      default:
        return "bg-red-100 text-red-800";
    }
  };

  const handleDownloadReport = () => {
    // Generate and download PDF report
    const reportData = {
      ...vendorData,
      generatedAt: new Date().toISOString(),
    };
    
    // Create a comprehensive report content
    const reportContent = `
VENDOR VERIFICATION REPORT - VendorVerify Pro
============================================

Company Name: ${vendorData.name}
GSTIN: ${vendorData.gstin}
PAN: ${vendorData.pan}

CONTACT INFORMATION:
Email: ${vendorData.email}
Phone: ${vendorData.phone}
Website: ${vendorData.website}
Address: ${vendorData.address}

VERIFICATION STATUS:
- GSTIN: ${vendorData.verificationStatus.gstin.toUpperCase()}
- PAN: ${vendorData.verificationStatus.pan.toUpperCase()}
- Documents: ${vendorData.verificationStatus.documents.toUpperCase()}
- Reputation: ${vendorData.verificationStatus.reputation.toUpperCase()}

Overall Status: ${vendorData.isVerified ? 'VERIFIED' : 'PENDING VERIFICATION'}
Premium Status: ${vendorData.isPremium ? 'ACTIVE' : 'NOT SUBSCRIBED'}

Report Generated: ${new Date().toLocaleString()}
Generated by: VendorVerify Pro Platform

For any queries, contact support@vendorverifypro.com
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${vendorData.name.replace(/\s+/g, '_')}_Verification_Report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <Building2 className="h-8 w-8 text-blue-600" />
              <h1 className="text-2xl font-bold text-gray-900">VendorVerify Pro</h1>
            </div>
            <Button variant="outline" onClick={() => navigate('/')}>
              Back to Home
            </Button>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <h2 className="text-3xl font-bold text-gray-900 mb-2">Vendor Dashboard</h2>
          <p className="text-gray-600">Manage your vendor profile and verification status</p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-6">
            {/* Verification Status Overview */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Shield className="h-5 w-5" />
                  Verification Status
                  <Badge className={`ml-auto ${vendorData.isVerified ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'}`}>
                    {vendorData.isVerified ? 'Verified' : 'Pending'}
                  </Badge>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex items-center gap-2">
                    {getStatusIcon(vendorData.verificationStatus.gstin)}
                    <span>GSTIN Verification</span>
                    <Badge className={getStatusColor(vendorData.verificationStatus.gstin)}>
                      {vendorData.verificationStatus.gstin}
                    </Badge>
                  </div>
                  <div className="flex items-center gap-2">
                    {getStatusIcon(vendorData.verificationStatus.pan)}
                    <span>PAN Verification</span>
                    <Badge className={getStatusColor(vendorData.verificationStatus.pan)}>
                      {vendorData.verificationStatus.pan}
                    </Badge>
                  </div>
                  <div className="flex items-center gap-2">
                    {getStatusIcon(vendorData.verificationStatus.documents)}
                    <span>Document Verification</span>
                    <Badge className={getStatusColor(vendorData.verificationStatus.documents)}>
                      {vendorData.verificationStatus.documents}
                    </Badge>
                  </div>
                  <div className="flex items-center gap-2">
                    {getStatusIcon(vendorData.verificationStatus.reputation)}
                    <span>Reputation Check</span>
                    <Badge className={getStatusColor(vendorData.verificationStatus.reputation)}>
                      {vendorData.verificationStatus.reputation}
                    </Badge>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Company Details */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Building2 className="h-5 w-5" />
                  Company Details
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm font-medium text-gray-500">Company Name</label>
                    <p className="text-gray-900">{vendorData.name}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">GSTIN</label>
                    <p className="text-gray-900">{vendorData.gstin}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">PAN</label>
                    <p className="text-gray-900">{vendorData.pan}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Website</label>
                    <p className="text-gray-900 flex items-center gap-1">
                      <Globe className="h-4 w-4" />
                      {vendorData.website}
                    </p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Email</label>
                    <p className="text-gray-900 flex items-center gap-1">
                      <Mail className="h-4 w-4" />
                      {vendorData.email}
                    </p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500">Phone</label>
                    <p className="text-gray-900 flex items-center gap-1">
                      <Phone className="h-4 w-4" />
                      {vendorData.phone}
                    </p>
                  </div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500">Address</label>
                  <p className="text-gray-900 flex items-center gap-1">
                    <MapPin className="h-4 w-4" />
                    {vendorData.address}
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Premium Upgrade */}
            <Card className="border-yellow-200 bg-gradient-to-br from-yellow-50 to-orange-50">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-yellow-800">
                  <Crown className="h-5 w-5" />
                  Upgrade to Premium
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-yellow-700 mb-4">
                  Unlock Director Due Diligence and advanced verification features
                </p>
                <Button 
                  className="w-full bg-yellow-600 hover:bg-yellow-700"
                  onClick={() => setShowPremiumModal(true)}
                >
                  View Plans
                </Button>
              </CardContent>
            </Card>

            {/* Quick Actions */}
            <Card>
              <CardHeader>
                <CardTitle>Quick Actions</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <Button 
                  variant="outline" 
                  className="w-full justify-start"
                  onClick={handleDownloadReport}
                >
                  <Download className="mr-2 h-4 w-4" />
                  Download Report
                </Button>
                <Button variant="outline" className="w-full justify-start">
                  <FileText className="mr-2 h-4 w-4" />
                  Update Documents
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>

      <PremiumUpgradeModal 
        open={showPremiumModal} 
        onOpenChange={setShowPremiumModal} 
      />
    </div>
  );
};

export default VendorDashboard;
